config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      get :participants
    end
  end
  resources :users
  root 'events#index'
  get 'auth/:provider/callback', to: "sessions#create"
  delete 'sign_out', to: "sessions#destroy", as: "sign_out"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  default_scope -> { order(created_at: :desc) }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comment, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship", foreign_key: "event_id", dependent: :destroy
  has_many :users_participating, through: :active_relationships,  source: :user
  validates :name, presence: true
  validates :location, presence: true
  validates :vacancies, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  validates :date, presence: true
  validates :imageUrl, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user, class_name: "User"
  belongs_to :event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship", foreign_key: "user_id", dependent: :destroy
  has_many :events_participating, through: :active_relationships,  source: :event
  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      id: auth['info']['id'],
      name: auth['info']['name'],
      image: auth['info']['image']
    )
  end

  def post(comment)
    comments << comment
  end

  def attend(event)
      events_participating << event
  end

  def default(event)
    events_participating.delete(event)
  end

  def attending?(event)
    events_participating.include?(event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def login_required
    redirect_to('/') if current_user.blank?
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      @event = Event.find(@comment.event_id)
      redirect_to @event, notice: 'Comentario Criado'
    else
      render :new
    end
  end

  def destroy
    event = Relationship.find(params[:id]).event
    current_user.default(event)
    redirect_to event
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id, :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :login_required, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def participants
    @title = "Participantes"
    @event = Event.find(params[:id])
    @participants = @event.users_participating
    render 'show_participants'
  end

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name, :location, :date, :vacancies, :description, :user_id, :imageUrl)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_auth
  def index
  end

  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @id = params[:relationship][:event_id]
    event = Event.find(@id)
    if event.vacancies > 0
      current_user.attend(event)
      vacancies = event.vacancies-1
      event.update(vacancies: vacancies)
      redirect_to event
    else
      redirect_to event, notice: 'Não temos vagas!'
    end
  end

  def destroy
    event = Relationship.find(params[:id]).event
    current_user.default(event)
    redirect_to event
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    session[:omniauth] = auth.except('extra')
    user = User.sign_in_from_omniauth(auth)
    session[:user_id] = user.id
    session[:image] = user.image
    redirect_to root_url, notice: "SIGNED IN"
  end

  def destroy
    session[:user_id] = nil
    session[:omniauth] = nil
    redirect_to root_url, notice: "SIGNED OUT"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <%= link_to gravatar_for(comment.event, size: 50), comment.event %>
  <span class="event"><%= link_to comment.event, comment.event %></span>
  <span class="content"><%= comment.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
  </span>
</li>

app/views/comments/_form.html.erb
<%= simple_form_for @comment do |f| %>
    <%= f.input :content, required: true%>
    <%= f.input :user_id, required: true, :as => :hidden, :input_html => { :value => current_user.id }%>
    <%= f.input :event_id, required: true, :as => :hidden, :input_html => { :value => 1}%>
    <%= f.button :submit, "Comentar" %>
<% end %>

app/views/comments/new.html.erb
<h1>Novo Comentario</h1>

<%= render 'form', comment: @comment %>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
    <%= f.input :name, required: true%>
    <%= f.input :location, required: true %>
    <%= f.input :vacancies, required: true%>
    <%= f.input :description, required: true%>
    <%= f.input :imageUrl, required: true%>
    <%= f.input :user_id, required: true, :as => :hidden, :input_html => { :value => current_user.id }%>
    <%= f.input :date, as: :date, required: true %>
    <%= f.button :submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Ver', @event %> |
<%= link_to 'Voltar', events_path %>

app/views/events/index.html.erb
<%= stylesheet_link_tag    'events/application',
            media: 'all', 'data-turbolinks-track': 'reload' %>

<p id="notice"><%= notice %></p>

<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Eventos
                    <small>cadastrados</small>
                </h1>
            </div>
        </div>

<div class="row">
  <% @events = @events.sort_by{|e| e[:date]}%>
  <% @events = @events.sort_by{|e| -e[:vacancies]}%>
    <% @events.each do |event| %>
    <% if event.status != 1 %>
      <div class="col-md-4 portfolio-item">
          <h2><%= event.name %></h2>
          <%= image_tag(event.imageUrl, width: '350', height: '200')%>
          <h3>
              <%= link_to 'Visualizar', event %>
          </h3>
          <% if current_user != nil %>
          <p>Compartilhar: <%= social_share_button_tag(event.name, :url => "eventize.com", :image => event.imageUrl, desc: event.description, via: "Eventize") %></p>
          <% if current_user.attending?(event) %>
            <p>Irei Participar!</p>
          <% end %>
          <% end %>
          <p>Localização: <%= event.location %></p>
          <p>Vagas: <%= event.vacancies %></p>
          <p>Data: <%= event.date.strftime("%d/%m/%Y") %></p>
          <p>Horario: <%= event.date.strftime("%I:%M%p") %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Novo Evento</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-fw fa-check"></i><%= @event.name %></h4>
      </div>
    </div>
  </div>
  <div class="col-md-8 portfolio-item">
    <%= image_tag(@event.imageUrl, width: '700', height: '400')%>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-fw fa-check"></i>Localização</h4>
      </div>
      <div class="panel-body">
        <p><%= @event.location %></p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-fw fa-check"></i>Data</h4>
      </div>
      <div class="panel-body">
        <p><%= @event.date.strftime("%d/%m/%Y")%></p>
        <p><%= @event.date.strftime("%I:%M%p")%></p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-fw fa-check"></i>Vagas</h4>
      </div>
      <div class="panel-body">
        <p>Vagas: <%= @event.vacancies%></p>
        <p>Participantes: <%= @event.users_participating.count %></p>
        <%= link_to 'Ver participantes', participants_event_path(@event.id) %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-fw fa-check"></i>Descrição</h4>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <textarea readonly class="form-control" rows="5" id="comment"><%= @event.description%></textarea>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Comentários</div>
  <table class="table">
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Comentario</th>
    </tr>
    <% @event.comment.each do |comment| %>
    <tr>
      <td></td>
      <td><%= comment.user.name %></td>
      <td><%= comment.content %></td>
    </tr>
    <% end %>
  </table>
</div>
<% if current_user != nil %>
<%= simple_form_for (current_user.comments.build) do |f| %>
    <%= f.input :content, required: true, label: "Comentario"%>
    <%= f.input :user_id, required: true, :as => :hidden, :input_html => { :value => current_user.id }%>
    <%= f.input :event_id, required: true, :as => :hidden, :input_html => { :value => @event.id }%>
    <%= f.button :submit, "Comentar"%>
<% end %>
  <% if current_user.id == @event.user_id %>
    <%= link_to 'Editar', edit_event_path(@event) %> |
    <%= link_to 'Excluir', @event, method: :delete, data: { confirm: 'Tem certeza?' } %> |
  <% end %>
<%= link_to 'Voltar', events_path %>
<%= social_share_button_tag(@event.name, :url => "eventize.com", :image => @event.imageUrl, desc: @event.description, via: "Eventize") %>
<% if current_user.attending?(@event) %>
  <%= simple_form_for (current_user.active_relationships.find_by(event_id: @event.id)), :html => { :method => "delete" } do |f| %>
    <%= f.button :submit, "Não pariticipar"%>
  <% end %>
<% else %>
  <%= simple_form_for (current_user.active_relationships.build) do |f| %>
      <%= f.input :event_id, required: true, :as => :hidden, :input_html => { :value => @event.id }%>
      <%= f.button :submit, "Participar"%>
  <% end %>
<% end %>
<% else %>
<%= link_to 'Voltar', events_path %>
<% end %>

app/views/events/show_participants.html.erb
<% provide(:title, @title) %>

<div class="panel panel-default">
  <div class="panel-heading">Participantes do evento <%= @event.name %></div>
  <table class="table">
    <tr>
      <th>#</th>
      <th>Nome</th>
    </tr>
    <tr>
      <% count = 0 %>
      <% @participants.each do |user| %>
        <td><%= count = count + 1 %></td>
        <td><%= user.name %></td>
      <% end %>
    </tr>
  </table>
</div>
<%= link_to 'Voltar', event_path(@event.id) %>

app/views/home/index.html.erb
<h1>Eventos Cadastrados</h1>
<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Eventize</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all',
                                 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
              <body>
          <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <%= link_to root_path do%> <h10 class="navbar-brand">Eventize</h10> <% end %>
              </div>
              <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <li><%= link_to root_path do%>Eventos<% end %></li>
                  <% if current_user %>
                  <li><%= link_to 'Novo Evento', new_event_path %></li>
                  <% end %>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <% if current_user %>
                  <li><a href="#profile"><%= current_user.name %></a></li>
                  <li><%= image_tag(current_user.image, width: '50', height: '50')%></li>
                  <li><%= link_to "Sair", 'sign_out', method: :delete%></li>
                  <% else %>
                  <li><%= link_to "auth/facebook" do%>Login<% end %></li>
                  <% end %>
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

          <div class="container">
            <div class="starter-template">
                <%= yield %>
            </div>
          </div><!-- /.container -->
        </body>
</html>